added registration testing
NasVa/trainee-ui-test pull request #1
Opened 2024-10-21 18:54 UTC by NasVa

Test cases: 
https://1drv.ms/x/c/dac2cc6f9147b7e2/EfMYYtJgRdxCvjBluyEfMDkBR97-YUlgTBQmxld0BQeowg

2024-10-23 08:43 UTC, maksimboukun requested changes

2024-10-23 08:43 UTC, maksimboukun commented on pom.xml
Вынеси версии в properties

2024-10-23 08:43 UTC, maksimboukun commented on src/main/java/org/nasva/constants/Constant.java
> +        public static final String ACCOUNT_CREATED_URL = "https://automationexercise.com/account_created";
Надо в ресурсы вынести

2024-10-23 08:43 UTC, maksimboukun commented on src/main/java/org/nasva/pages/CreatedAccountPage.java
> +    private final String accountCreatedString = "Account Created!";
сделай константами в этом классе

2024-10-23 08:43 UTC, maksimboukun commented on src/main/java/org/nasva/pages/LoginPage.java
> +    private final String signupString = "New User Signup!";
Константы

2024-10-23 08:43 UTC, maksimboukun commented on src/main/java/org/nasva/pages/RegistrationPage.java
> +    private final String registrationString = "Enter Account Information";
Константы

2024-10-23 08:43 UTC, maksimboukun commented on src/main/java/org/nasva/pages/RegistrationPage.java
> +                .stream().map(SelenideElement::toString).collect(Collectors.toList()));
а зачем println вообще в тестах?

2024-10-23 23:57 UTC, NasVa commented on src/main/java/org/nasva/pages/RegistrationPage.java
> +                .stream().map(SelenideElement::toString).collect(Collectors.toList()));
это я чекала, забыла убрать

2024-10-30 13:26 UTC, maksimboukun approved these changes

2024-10-30 22:42 UTC, merged